import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import styles from 'styles/Home.module.css';

const Home: NextPage = () => {
	const router = useRouter();
	return (
		<div className={styles.container}>
			<Head>
				<title>Lottery dApp</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>Welcome to Lottery dApp!</h1>

				<p className={styles.description}>
					Get started by clicking on a tile!
					{/* <code className={styles.code}>pages/index.tsx</code> */}
				</p>

				<div className={styles.grid}>
					<div
						onClick={() => router.push('/check-state')}
						className={styles.card}
					>
						<h2>Check State &rarr;</h2>
						{/* <p>Tokens represent voting weight.</p> */}
					</div>
					<div
						onClick={() => router.push('/open-bets')}
						className={styles.card}
					>
						<h2>Open Bets &rarr;</h2>
					</div>
					<div
						onClick={() => router.push('/top-up-account-tokens')}
						className={styles.card}
					>
						<h2>Top Up Account Tokens &rarr;</h2>
					</div>
					<div
						onClick={() => router.push('/display-balance')}
						className={styles.card}
					>
						<h2>Display Balance &rarr;</h2>
					</div>
					<div onClick={() => router.push('/bet')} className={styles.card}>
						<h2>Bet &rarr;</h2>
					</div>
					<div
						onClick={() => router.push('/close-bets')}
						className={styles.card}
					>
						<h2>Close Bets &rarr;</h2>
					</div>
					<div
						onClick={() => router.push('/check-player-prize')}
						className={styles.card}
					>
						<h2>Check Player Prize &rarr;</h2>
					</div>
					<div onClick={() => router.push('/withdraw')} className={styles.card}>
						<h2>Withdraw &rarr;</h2>
					</div>
					<div
						onClick={() => router.push('/burn-tokens')}
						className={styles.card}
					>
						<h2>Burn Tokens &rarr;</h2>
					</div>
				</div>
			</main>

			<footer className={styles.footer}>
				<p>Encode Solidity Week 5 Project - Group 2</p>
			</footer>
		</div>
	);
};

export default Home;
